---
- name: Install shell packages
  become: true
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - curl
      - fzf
      - tmux
      - ripgrep
      - bat
    state: present
    update_cache: true

- name: Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ shell_ohmyzsh_dir }}"
    version: "146461f7c6d95f4ba1220559d66eb113418b40a8"
    depth: 1

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ shell_ohmyzsh_dir }}/custom/plugins/zsh-autosuggestions"
    version: "85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5"
    depth: 1

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ shell_ohmyzsh_dir }}/custom/plugins/zsh-syntax-highlighting"
    version: "2fc57d63067c18b1100ecdbf684fa5baf49459d1"
    depth: 1

- name: Configure Zsh
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ shell_home }}/.zshrc"
    mode: "0644"
    backup: true

- name: Set Zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ shell_user }}"
    shell: /usr/bin/zsh
