---
shell_user: "{{ ansible_user_id }}"
shell_home: "{{ ansible_env.HOME }}"

ohmyzsh_dir: "{{ shell_home }}/.oh-my-zsh"

zsh_plugins:
  - git
  - history
  - zsh-autosuggestions
  - zsh-syntax-highlighting