---
conda_distribution: miniforge

conda_install_dir: "{{ ansible_env.HOME }}/miniforge3"

conda_solver: libmamba

conda_channel_priority: strict

conda_channels:
  - conda-forge
  - bioconda

conda_miniforge_version: "latest"
conda_installer_name: "Miniforge3-Linux-{{ ansible_architecture }}.sh"
conda_installer_url: >-
  https://github.com/conda-forge/miniforge/releases/latest/download/{{ conda_installer_name }}
conda_installer_path: "/tmp/{{ conda_installer_name }}"