---
- name: Configure Ocelotl workstation
  hosts: workstation

  roles:
    - apt
    - common
    - ansible
    - r
    - conda
    - java
    - docker
    - nextflow
    - vscode
    - shell
    - obsidian
    - godot
    - syncthing
    - role: libresprite
      tags:
      - libresprite